### ISSUE TITLE
MacOS Big Sur: master is broken

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#3191]
Current master fails to compile on MacOS Big Sur with Xcode-13.2.1 (the latest that one can install on it).

It fails with Xcode clang++, with Macports-installed GCC-12, and Macports-installed Clang-15. Boost-1.76 is installed in /opt/local.

Example:
```
clang++-mp-15 -fPIC -fvisibility=hidden -fstack-protector -m64 -pthread -stdlib=libc++ -march=native -std=c++20 -
D_REENTRANT  -std=c++20 -stdlib=libc++ -O3 -I/opt/local/include -isysroot /Applications/Xcode.app/Contents/Develo
per/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DBOTAN_IS_BEING_BUILT -Wall -Wextra -Wpedantic -Wshadow 
-Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wshorten-6
4-to-32 -Wcomma -Wdocumentation  -I build/include -isystem build/include/external -c src/lib/utils/socket/uri.cpp
 -o build/obj/lib/utils_socket_uri.o
In file included from src/lib/utils/socket/socket.cpp:20:
In file included from /opt/local/include/boost/asio.hpp:20:
In file included from /opt/local/include/boost/asio/associated_allocator.hpp:20:
/opt/local/include/boost/asio/detail/type_traits.hpp:89:12: error: no member named 'result_of' in namespace 'std'
using std::result_of;
      ~~~~~^
In file included from src/lib/utils/socket/socket.cpp:20:
In file included from /opt/local/include/boost/asio.hpp:21:
In file included from /opt/local/include/boost/asio/associated_executor.hpp:20:
In file included from /opt/local/include/boost/asio/execution/executor.hpp:20:
/opt/local/include/boost/asio/execution/execute.hpp:101:20: error: no member named 'result_of' in namespace 'boost::asio'
```

With Clang-15:
[make-out.txt](https://github.com/randombit/botan/files/10447799/make-out.txt)
[conf-out.txt](https://github.com/randombit/botan/files/10447800/conf-out.txt)

With Clang from Xcode-13.2.1:
```
clang++ -fPIC -fvisibility=hidden -fstack-protector -m64 -pthread -stdlib=libc++ -march=native -std=c++20 -D_REEN
TRANT  -std=c++20 -stdlib=libc++ -O3 -I/opt/local/libexec/boost/1.81/include -I/opt/local/include -isysroot /Appl
ications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DBOTAN_IS_BEING_BUILT 
-Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpoi
nter-arith -Wcast-qual -Wshorten-64-to-32 -Wcomma -Wdocumentation  -I build/include -isystem build/include/extern
al -c src/lib/hash/checksum/adler32/adler32.cpp -o build/obj/lib/hash_checksum_adler32.o
src/lib/filters/threaded_fork.cpp:76:43: error: 'release' is unavailable
   m_thread_data->m_input_ready_semaphore.release(m_threads.size());
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/semaphore:200:10: note: 'release' has been explicitly marked unavailable here
    void release(ptrdiff_t __update = 1)
         ^
src/lib/filters/threaded_fork.cpp:132:43: error: 'release' is unavailable
   m_thread_data->m_input_ready_semaphore.release(total_ports());
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/semaphore:200:10: note: 'release' has been explicitly marked unavailable here
    void release(ptrdiff_t __update = 1)
         ^
src/lib/filters/threaded_fork.cpp:146:46: error: 'acquire' is unavailable
      m_thread_data->m_input_ready_semaphore.acquire();
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/semaphore:205:10: note: 'acquire' has been explicitly marked unavailable here
```
[make-out.txt](https://github.com/randombit/botan/files/10447922/make-out.txt)

Will post more data as it becomes available.

**Comment by reneme** [comment]
Mhh, with the move to C++20 (and Clang 14) we probably left XCode 13 in the dust.

Regarding the compilers from MacPorts: These are trying to use the STL bundled with XCode (see: `-isysroot /Appl
ications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`). And (apparently) that does not provide the library features needed to compile `master`, I'm afraid.

Potentially you can work around this by compiling/linking against a more recent STL. Without any guarantees: Maybe this provides a few helpful pointers: https://trac.macports.org/ticket/62426

**Comment by randombit** [comment]
The semaphore limitations we can probably work around by moving `Threaded_Fork` into its own module, at least then it could be easily disabled without having to also disable large amounts of other unrelated code.

Ultimately though, there is a reason that the support policy is limited to the very latest version of XCode. Already XCode 14 is far behind recent Clang/GCC/MSVC in C++20 support.

**Comment by mouse07410** [comment]
> with the move to C++20 (and Clang 14) we probably left XCode 13 in the dust.

1. Is it a "done deal"? I'd hate to see Xcode 13 dumped lile this.
2. I tried to compile without `-isysroot ...`. To my pleasure it did not fail to locate the SDK - but it could not find the STL (I assume) methods:
```
 "__ZSt17rethrow_exceptionSt13exception_ptr", referenced from:
      __ZNSt3__16futureIN5Botan6BigIntEE3getEv in pubkey_rsa.o
      __ZN5boost4asio6detail9scheduler10do_run_oneERNS1_27conditionally_enabled_mutex11scoped_lockERNS1_21scheduler_thread_infoERKNS_6system10error_codeE in utils_socket.o
      __ZN5boost4asio6detail9scheduler10do_run_oneERNS1_27conditionally_enabled_mutex11scoped_lockERNS1_21scheduler_thread_infoERKNS_6system10error_codeE in utils_socket_udp.o
```
and many similar ones.

I tried adding `-D_LIBCPP_DISABLE_AVAILABILITY`, but it did not help. 

> Ultimately though, there is a reason that the support policy is limited to the very latest version of XCode. Already XCode 14 is far behind recent Clang/GCC/MSVC in C++20 support.

Well, as I posted above - Clang-15 and GCC-12 also fail to compile and/or link the `master`. And these (AFAIK) fully support C++20 standard...?

**Comment by reneme** [comment]
Clang 15 supports C++20 but for the new library features it needs to have access to a recent implementation of the STL (`libc++`) as well. Clang 15 alone won't do the trick.

Now, I don't use MacPorts, but if you install Clang 15 via `brew install llvm` it prints some valuable guidance on how to use the `libc++` implementation it shipped with:

```
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"

llvm is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
```

As mentioned, I don't have macOS Big Sur handy, but on Ventura the following worked for me:

```bash
# Install Clang 15 (along with its libc++)
brew install llvm

# Configure botan to use clang++ 15 and its libc++
./configure.py                                                                       \
  --extra-cxxflags='-I/opt/homebrew/opt/llvm/include'                                \
  --ldflags='-L/opt/homebrew/opt/llvm/lib -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++' \
  --cc-bin=/opt/homebrew/opt/llvm/bin/clang++

# Build as usual
make
```

I'm not sure how this works with Clang 15 installed via MacPorts, unfortunately. Most likely you'll need to use different paths for `--ldflags`, `--extra-cxxflags` and `--cc-bin` but the idea should be similar.

Side note: In fact, using these steps, I can use more C++20 library features (e.g. as tried in #3188) than with XCode 14. So that shows me that the steps above switch the used `libc++` version successfully.

**Comment by mouse07410** [comment]
@reneme thank you - here's the config that turned out working for me:
```
./configure.py --prefix=/opt/local --with-boost --cc-bin='/opt/local/bin/clang++-mp-15' --extra-cxxflags='-I/opt/local/libexec/llvm-15/include' --ldflags='-L/opt/local/libexec/llvm-15/lib -Wl,-rpath,/opt/local/libexec/llvm-15/lib' --with-os-features=security_framework,apple_keychain,commoncrypto,getentropy --with-commoncrypto --with-lzma --with-bzip2 --with-zlib --with-sqlite3 --with-python-version=3.9 --with-sphinx --with-pdf --system-cert-bundle=/opt/local/share/curl/curl-ca-bundle.crt --cc-abi-flags='-march=native'  2>&1 | tee conf-out.txt
```

Note, that I had to install and use Boost-1.81, as somehow it seemed to have problems with the default Boost-1.76 on my machine. Perhaps, it was caused by other errors, I did not investigate any further.

**Comment by reneme** [comment]
Glad that you got it to work!

> Oh, semi-related question: is there a way to configure Botan so that it installs botan executable as, e.g., botan3 in the destination directory?

`./configure --program-suffix 3` should do the trick. For the record, there's also `--library-suffix` if you happen to need that.

**Comment by reneme** [comment]
I'm closing as completely, if don't mind.
