### ISSUE TITLE
32bit Build fails on GCC 4.9 

### ISSUE THREAD

**Issue by reneme** [randombit/botan#2139]
I'm currently trying to update the [Botan's conan recipe](https://github.com/bincrafters/conan-botan/pull/14) to 2.12.0 and run into [a build issue with 32bit GCC 4.9](https://travis-ci.com/bincrafters/conan-botan/jobs/243772035):

```
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/xmmintrin.h: In function 'bool Botan::{anonymous}::read_rdseed(Botan::secure_vector<unsigned int>&)':
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/xmmintrin.h:1238:1: error: inlining failed in call to always_inline 'void _mm_pause()': target specific option mismatch
 _mm_pause (void)
 ^
botan_all_rdseed.cpp:65:18: error: called from here
       _mm_pause();
                  ^
```

All other compilers (i.e. 64bit GCC 4.9, 32bit and 64bit GCC 5 and newer, 32bit and 64bit clang 3.9 and newer, as well as Xcode 8.3 and newer) compile it perfectly fine.

AFAICS: The problematic `_mm_pause()` intrinsic was introduced [in this PR](https://github.com/randombit/botan/pull/2007).

Furthermore, I see a few warnings, that might hint at missing compiler flags:
```
botan_all_internal.h: In member function 'Botan::native_simd_type Botan::SIMD_4x32::raw() const':
botan_all_internal.h:5540:36: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
       native_simd_type raw() const { return m_simd; }
                                    ^
```

**Comment by randombit** [comment]
Seems like a bug in GCC since _mm_pause should compile to a NOP on CPUs which don't support PAUSE. But of course just because it's a bug in old GCC doesn't mean we're not stuck with it. [One reason I am fond of periodically dumping support for older compilers...]

Only affects x86-32 since x86-64 implicitly includes SSE2 which is where the PAUSE instruction was added.

**Comment by reneme** [comment]
The fix will allow a default-configured build on 32bit gcc 4.9 again, right? I’d patch it into the Conan recipe then and re-enable that Compiler over there to double check

**Comment by randombit** [comment]
Yes db32722 resolved it for me

**Comment by randombit** [comment]
The warnings about ABI are a different issue though one that should also be addressed in 2.12.1

**Comment by reneme** [comment]
For the record: This is the [CI job in the conan recipe](https://travis-ci.com/bincrafters/conan-botan/jobs/243977401) for GCC 4.9 32bits with the db32722 patch.

**Comment by reneme** [comment]
First of all: Thanks a lot for the quick patch release!

> The warnings about ABI are a different issue though one that should also be addressed in 2.12.1

I still see [these ABI warnings in Bincrafter's Travis](https://travis-ci.com/bincrafters/conan-botan/jobs/245340853#L648), though? Problematic?

**Comment by randombit** [comment]
@reneme ack I forgot about this. I don't think it's a huge issue because the symbols are internal; it changes the ABI when these functions are used, but that change isn't visible externally to library users. But it should be fixed. I will open a new issue to track this.

**Comment by randombit** [comment]
On another look that warning looks really odd, because it is happening in a x86-64 build, and the base amd64 ISA includes SSE/SSE2. So how could we be compiling "without SSE enabled"?
