### ISSUE TITLE
Amalgamation build fails on MSVC with C2332 errors in PKCS11 module (3.11.0 regression)

### ISSUE THREAD

**Issue by arekmula** [randombit/botan#5482]
Hey, 

Botan 3.11.0 amalgamation build fails on MSVC (MSVC 19.43.34809.0 (Visual Studio 2022, toolset 14.43)) with multiple C2332: 'struct': missing tag name errors originating from the PKCS11 module. This worked in 3.10.0. It seems it was introduced within [this changes](https://github.com/randombit/botan/pull/4540).

Here's the command I used to configure the amalgamation build:
```
./configure.py --build-targets=static --without-documentation --cc-abi-flags=" " --extra-cxxflags=" " --cc=msvc --cpu=x86_64 --os=windows --disable-experimental-features --enable-deprecated-features --amalgamation --msvc-runtime=MD --without-pkg-config
```

And here are the errors:
```
botan_all.cpp(111290): error C2332: 'struct': missing tag name
botan_all.cpp(111290): error C2144: syntax error: 'Botan::PKCS11::`anonymous-namespace'::<unnamed-tag>' should be preceded by ')'
botan_all.cpp(111290): error C2144: syntax error: 'Botan::PKCS11::`anonymous-namespace'::<unnamed-tag>' should be preceded by ';'
botan_all.cpp(111290): error C2059: syntax error: ')'
botan_all.cpp(111290): error C2059: syntax error: '{'
botan_all.cpp(111290): error C2143: syntax error: missing ';' before '{'
botan_all.cpp(111290): error C2447: '{': missing function header (old-style formal list?)
botan_all.cpp(111297): error C2332: 'struct': missing tag name
botan_all.cpp(111297): error C2144: syntax error: 'Botan::PKCS11::`anonymous-namespace'::<unnamed-tag>' should be preceded by ')'
botan_all.cpp(111297): error C2144: syntax error: 'Botan::PKCS11::`anonymous-namespace'::<unnamed-tag>' should be preceded by ';'
botan_all.cpp(111297): error C2059: syntax error: ')'
botan_all.cpp(111297): error C2059: syntax error: '{'
botan_all.cpp(111297): error C2143: syntax error: missing ';' before '{'
botan_all.cpp(111297): error C2447: '{': missing function header (old-style formal list?)
```

It points to this part of the code:
```
std::strong_ordering operator<=>(const Version& left, const Version& right) {
   // Compare both versions by concatenating their bytes: major || minor
   auto version_value = [](const Version& v) -> uint16_t {
      return static_cast<uint16_t>(v.major) << 8 | static_cast<uint16_t>(v.minor);
   };
   return version_value(left) <=> version_value(right);
}

bool operator==(const Version& left, const Version& right) {
   return left.major == right.major && left.minor == right.minor;
}

Version version_of(const Interface& interface) {
   // PKCS #11 CK_INTERFACE documentation:
   //   pFunctionList - the interface function list which must always begin with
   //   a CK_VERSION structure as the first field
   return *reinterpret_cast<Version*>(interface.pFunctionList);
}
```

MSVC appears unable to resolve operator overloads on the Version type in amalgamation context. GCC and Clang are fine about it.

**Comment by randombit** [comment]
@FAlbertDev could you look into this?

**Comment by randombit** [comment]
Might want to try MSVC 19.44 - that seems to be working fine in CI for the amalgamation build

**Comment by FAlbertDev** [comment]
I can reproduce the issue with MSVC 19.44 (and the same configure.py config). I'll investigate further 👍

**Comment by FAlbertDev** [comment]
Update: It seems that some Windows Header has some `#define interface struct`, so the parameter name `interface` causes the problem.

**Comment by randombit** [comment]
Fixed now on master, thanks for the report. Patch from #5486 should apply directly to 3.11.0
