### PR TITLE
boost 1.70 compatibility

### LINKED ISSUE #1880: Fails to build with Boost 1.70 (Beta1)
Regressed by boostorg/asio@a72fbb0b867f:
```c++
src/cli/tls_http_server.cpp:438:31: error: no member named 'get_io_service' in
      'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
                   m_acceptor.get_io_service(),
                   ~~~~~~~~~~ ^
src/cli/tls_proxy.cpp:373:31: error: no member named 'get_io_service' in
      'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
                   m_acceptor.get_io_service(),
                   ~~~~~~~~~~ ^
```

### PR DESCRIPTION
**Pull request by RvdE**
Fixes #1880

### CODE REVIEW

**Comment by randombit** [comment]
Thanks
