### ISSUE TITLE
Dangling reference warning with GCC 13

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3851]
Introduced in #3820 

```
src/cli/tls_utils.cpp: In static member function ‘static std::string Botan_CLI::TLS_Client_Hello_Reader::format_hello(const std::variant<Botan::TLS::Client_Hello_13, Botan::TLS::Client_Hello_12>&)’:
src/cli/tls_utils.cpp:126:22: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  126 |          const auto& hello_base =
      |                      ^~~~~~~~~~
src/cli/tls_utils.cpp:127:23: note: the temporary was destroyed at the end of the full expression ‘std::visit<Botan_CLI::TLS_Client_Hello_Reader::format_hello(const std::variant<Botan::TLS::Client_Hello_13, Botan::TLS::Client_Hello_12>&)::<lambda(const auto:62&)>, const variant<Botan::TLS::Client_Hello_13, Botan::TLS::Client_Hello_12>&>(<lambda closure object>Botan_CLI::TLS_Client_Hello_Reader::format_hello(const std::variant<Botan::TLS::Client_Hello_13, Botan::TLS::Client_Hello_12>&)::<lambda(const auto:62&)>(), (* & hello))’
  127 |             std::visit([](const auto& ch) -> const Botan::TLS::Client_Hello& { return ch; }, hello);
      |             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:1519: build/obj/cli/tls_utils.o] Error 1
```

cc @reneme maybe this is harmless, idk, haven't looked into it carefully yet.
