### ISSUE TITLE
error: 'kSecRandomDefault' was not declared in this scope

### ISSUE THREAD

**Issue by noloader** [randombit/botan#528]
I'm working on OS X 10.8.5. The machine has MacPorts 2.3.4 installed. MacPorts is a third party package provider, and it offers modern GCC's.

```
$ make
...
/opt/local/bin/g++-mp-6  -m64 -pthread -fstack-protector -Wa,-q -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp -o build/obj/lib/entropy_darwin_secrandom.o
./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp: In member function 'virtual void Botan::Darwin_SecRandom::poll(Botan::Entropy_Accumulator&)':
./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp:20:31: error: 'kSecRandomDefault' was not declared in this scope
    if(0 == SecRandomCopyBytes(kSecRandomDefault, buf.size(), buf.data()))
                               ^~~~~~~~~~~~~~~~~
./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp:20:72: error: 'SecRandomCopyBytes' was not declared in this scope
    if(0 == SecRandomCopyBytes(kSecRandomDefault, buf.size(), buf.data()))
                                                                        ^
Makefile:639: recipe for target 'build/obj/lib/entropy_darwin_secrandom.o' failed
make: *** [build/obj/lib/entropy_darwin_secrandom.o] Error 1
```

This may be related on Stack Overflow: [kSecRandomDefault not found?](http://stackoverflow.com/q/8639091). I'm not sure if the way to proceed is to simply add `<Security/SecRandom.h>`, or if something more needs to be done for this configuration.

And the configure line:

```
$ ./configure.py --os=darwin --cc=gcc --cpu=x86_64 --cc-bin=/opt/local/bin/g++-mp-6 --cc-abi-flags="-Wa,-q"
   INFO: Platform: OS="Darwin" machine="x86_64" proc="i386"
   INFO: Canonicalizized CPU target x86_64 to x86_64/x86_64
   INFO: Target is gcc-darwin-x86_64-x86_64
   INFO: Skipping, dependency failure - sessions_sqlite3
   INFO: Skipping, incompatible CPU - mp_x86_32 simd_altivec
   INFO: Skipping, incompatible OS - beos_stats cryptoapi_rng win32_stats
   INFO: Skipping, incompatible compiler - mp_x86_32_msvc
   INFO: Skipping, only used if needed or requested - dyn_load mp_generic simd_scalar
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl pkcs11 sqlite3 tpm zlib
   INFO: Using MP module mp_x86_64
   INFO: Using SIMD module simd_sse2
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 aont asn1 auto_rng base base64 bcrypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cfb chacha chacha20poly1305 clmul cmac codec_filt comb4p compression crc24 crc32 cryptobox ctr curve25519 darwin_secrandom datastor des dev_random dh dl_algo dl_group dlies dsa eax ec_gfp ec_group ecb ecc_key ecdh ecdsa ecgdsa ecies eckcdsa egd elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gost_28147 gost_3410 gost_3411 has160 hash hash_id hex hkdf hmac hmac_drbg hmac_rng hres_timer http_util idea idea_sse2 if_algo kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion locking_allocator mac mars mce mceies md2 md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp mp_x86_64 noekeon noekeon_simd nr numbertheory ocb ofb oid_lookup openpgp par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 proc_walk pubkey rc2 rc4 rc5 rc6 rdrand rdseed rfc3394 rfc6979 rmd128 rmd160 rng rsa rw safer salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_sse2 sha2_32 sha2_64 simd simd_sse2 siphash siv skein sp800_108 sp800_56c srp6 stream system_rng tea threefish threefish_avx2 tiger tls tss twofish unix_procs utils whirlpool x509 x919_mac x931_rng xtea xtea_simd xts
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Botan 1.11.31 (unreleased undated) build setup is complete
```

**Comment by noloader** [comment]
This seemed to work through the issue. It tested OK on the non-MacPorts gear, including Xcode on 10.8.5:

```
$ git diff
diff --git a/src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp b/src/lib/ent
index 4f1ed87..0a6b859 100644
--- a/src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp
+++ b/src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp
@@ -7,6 +7,7 @@
 
 #include <botan/internal/darwin_secrandom.h>
 #include <Security/Security.h>
+#include <Security/SecRandom.h>
 
 namespace Botan {
```
-----

However, I'm having trouble testing it OS X 10.9 using Clang:

```
$ ./configure.py --os=darwin --cpu=x86_64 --cc=clang  
   INFO: Platform: OS="Darwin" machine="x86_64" proc="i386"
   INFO: Canonicalizized CPU target x86_64 to x86_64/x86_64
   INFO: Target is clang-darwin-x86_64-x86_64
   INFO: Skipping, dependency failure - sessions_sqlite3
...

$ make src/lib/entropy/darwin_secrandom/darwin_secrandom.o
clang++  -m64 -pthread -std=c++11 -D_REENTRANT -fstack-protector -O3   -c -o src/lib/entropy/darwin_secrandom/darwin_secrandom.o src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp
src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp:8:10: fatal error: 
      'botan/internal/darwin_secrandom.h' file not found
#include <botan/internal/darwin_secrandom.h>
         ^
1 error generated.
<builtin>: recipe for target 'src/lib/entropy/darwin_secrandom/darwin_secrandom.o' failed
make: *** [src/lib/entropy/darwin_secrandom/darwin_secrandom.o] Error 1
...
```

**Comment by noloader** [comment]
Cancel the last part about trouble testing the change. A "straight make" worked as expected:

```
$ make
...
clang++  -m64 -pthread -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -c ./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp -o build/obj/lib/entropy_darwin_secrandom.o
```

**Comment by randombit** [comment]
SecRandom.h seems to be the actual location where SecRandomCopyBytes is defined 

https://opensource.apple.com/source/Security/Security-55178.0.1/sec/Security/SecRandom.h

But this file uses Security/Security.h, which should include SecRandom.h:

https://opensource.apple.com/source/Security/Security-55178.0.1/sec/Security/Security.h

I wonder what your systems Security.h has - perhaps some versions of OS X are missing this include of SecRandom.h in this file.

In any case the file *only* uses definitions from SecRandom.h so it should probably use that in favor of Security.h in any case.

**Comment by cordney** [comment]
I checked this by looking into an Xcode 5.1.1 image: In the 10.8 SDK, SecRandom.h is not included in Security.h, while starting from the 10.9 SDK, it *is* included from Security.h.

**Comment by randombit** [comment]
Fixed, thanks
