### ISSUE TITLE
Error 'botan_privkey_export_encrypted_pbkdf_iter': Use botan_privkey_view_encrypted_{der,pem}

### ISSUE THREAD

**Issue by kre-medisoftware** [randombit/botan#4869]
Botan-Version 3.8.1
The Botan-Library is build as Amalgamation-Build

When i include the botan_all.cpp the Compiler Visual Studio 2022 list this error:

How can i resolve this ?
The same build with Botan-Version 3.6.1 works without errors.

```
C:\...\botan\botan_all.cpp(64832,11): error C4996: 'botan_privkey_export_encrypted_pbkdf_iter': Use botan_privkey_view_encrypted_{der,pem}
C:\...\botan\botan_all.cpp(4226,52): error C2672: "Botan::bitvector_base<Botan::secure_allocator>::blockwise_processing_callback_trait<FnT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>>::apply": keine übereinstimmende überladene Funktion gefunden
C:\...\botan\botan_all.cpp(4226,52): error C2672:         with
C:\...\botan\botan_all.cpp(4226,52): error C2672:         [
C:\...\botan\botan_all.cpp(4226,52): error C2672:             FnT=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>,
C:\...\botan\botan_all.cpp(4226,52): error C2672:             OtherT=Botan::secure_bitvector
C:\...\botan\botan_all.cpp(4226,52): error C2672:         ]
    C:\...\botan\botan_all.cpp(4265,35):
    kann "auto Botan::bitvector_base<Botan::secure_allocator>::blockwise_processing_callback_trait<FnT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>>::apply(FnT,Botan::bitvector_base<Botan::secure_allocator>::size_type,BlockTs...)" sein
        with
        [
            FnT=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>,
            OtherT=Botan::secure_bitvector
        ]
        C:\...\botan\botan_all.cpp(4226,52):
        Die zugeordneten Einschränkungen werden nicht erfüllt.
            C:\...\botan\botan_all.cpp(4264,25):
            Die Einschränkung wurde nicht erfüllt
    C:\...\botan\botan_all.cpp(4226,52):
    der Vorlageninstanziierungskontext (der älteste zuerst) ist
        C:\...\botan\botan_all.cpp(46452,11):
        Siehe Verweis auf die gerade kompilierte Instanziierung "Botan::bitvector_base<Botan::secure_allocator> &Botan::bitvector_base<Botan::secure_allocator>::operator &=<T>(const OtherT &)" der Funktions-Vorlage.
        with
        [
            T=Botan::secure_bitvector,
            OtherT=Botan::secure_bitvector
        ]
        C:\...\botan\botan_all.cpp(3906,10):
        Siehe Verweis auf die gerade kompilierte Instanziierung "bool Botan::bitvector_base<Botan::secure_allocator>::full_range_operation<Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>,Botan::bitvector_base<Botan::secure_allocator>,const OtherT>(FnT &&,Botan::bitvector_base<Botan::secure_allocator> &,const OtherT &)" der Funktions-Vorlage.
        with
        [
            OtherT=Botan::secure_bitvector,
            FnT=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>
        ]
        C:\...\botan\botan_all.cpp(4356,17):
        Siehe Verweis auf die gerade kompilierte Instanziierung "bool Botan::bitvector_base<Botan::secure_allocator>::range_operation<_Ty,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>>(FnT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>)" der Funktions-Vorlage.
        with
        [
            _Ty=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>,
            OtherT=Botan::secure_bitvector,
            FnT=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>
        ]
        C:\...\botan\botan_all.cpp(4337,20):
        Siehe Verweis auf die gerade kompilierte Instanziierung "bool Botan::bitvector_base<Botan::secure_allocator>::_process_in_fully_aligned_blocks_of<uint32_t,FnT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>>(FnT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned> &,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned> &)" der Funktions-Vorlage.
        with
        [
            FnT=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>,
            OtherT=Botan::secure_bitvector
        ]
        C:\...\botan\botan_all.cpp(4290,46):
        Siehe Verweis auf die gerade kompilierte Instanziierung "bool Botan::bitvector_base<Botan::secure_allocator>::blockwise_processing_callback_trait<FnT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<Botan::bitvector_base<Botan::secure_allocator>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>,Botan::bitvector_base<Botan::secure_allocator>::BitRangeOperator<const OtherT,Botan::bitvector_base<Botan::secure_allocator>::BitRangeAlignment::byte_aligned>>::apply_on_full_blocks<unsigned int,const Botan::word>(FnT,std::span<unsigned int,4294967295>,std::span<const Botan::word,4294967295>)" der Funktions-Vorlage.
        with
        [
            FnT=Botan::bitvector_base<Botan::secure_allocator>::&=::<lambda_1>,
            OtherT=Botan::secure_bitvector
        ]
```

**Comment by kre-medisoftware** [comment]
The Project does not change and the build of the amalgamation-files (botan_all.cpp, botan_all.h) is startet from script, where only the include from botan-version changes 
Botan-3.6.1\src\...
Botan-3.8.1\src\...

Today i tried to build with some older versions of Botan. With Botan 3.7.1 the Build runs successful, With Botan 3.8.0 i get the same error i have descriped above

For running Botan 3.7.1 i have to change a little bit, because EC_Point is deprecated

Here is the build-commandline
`python3 configure.py --cc=msvc --os=windows --prefix=%cd% --cpu=x86 --msvc-runtime=MT --amalgamation --disable-shared --disable-deprecated-features`

The ReleaseNotes list a lot of changes between 3.7.1 and 3.8.0

**Comment by randombit** [comment]
Ah I see now the problem, while we silence most deprecation warnings when compiling the amalgamation there is slightly different logic in `ffi.h`

**Comment by randombit** [comment]
Fixed now on master you can apply #4872 as a patch to 3.8.1 if required
