### PR TITLE
Add certificate creation to FFI

### PR DESCRIPTION
**Pull request by arckoor**
Adds a "minimal" certificate builder to the FFI (extensions I'll do in a separate PR)

- First commit is #4996 squashed into one commit
- Second commit are the changes needed to make it build on master, along with extra fixes. My hope is that this can be cherry picked and used in #4996, either in whole or at least in part
- Last commit is what this PR would actually like to add

I would've liked to test more in python, but `X509Cert` doesn't provide most of the things added in #5188, and I don't currently have the time to add them myself (cc @reneme maybe, but I'll do more extensive testing on the cpp side anyway, so not "critical")

### CODE REVIEW

**Comment by moritzschmitt** [comment]
All the new declarations in `ffi.h` are tagged `BOTAN_FFI_EXPORT(3, 13)`, but 3.13.0 was tagged on 2026-08-13 and this branch is based on a commit after that tag. As tagged, the header claims these functions exist in the released 3.13.0. They need to be `(3, 14)`.

Since this would be the first 3.14 FFI addition, the FFI API date also needs bumping in the four places listed at the top of `src/lib/ffi/info.txt` (`info.txt`, `BOTAN_FFI_API_VERSION` in `ffi.h`, `botan_ffi_supports_api` in `ffi.cpp`, `BOTAN_FFI_VERSION` in `botan3.py`). That is how the 3.13 date was introduced in af3887268.

Same applies to the RFC 3779 additions in #5853.

File: src/lib/ffi/ffi_cert.cpp [hunk 1]
```diff
@@ -1032,6 +1067,339 @@ const char* botan_x509_cert_validation_status(int code) {
...
+   });
+#else
+   BOTAN_UNUSED(subject_req, issuing_cert, issuing_key, rng, not_before, not_after, serial_number, hash_fn, padding);
+   return BOTAN_FFI_ERROR_NOT_IMPLEMENTED;
+#endif
+}
+
 int botan_x509_crl_load_file(botan_x509_crl_t* crl_obj, const char* crl_path) {
    if(Botan::any_null_pointers(crl_obj, crl_path)) {
       return BOTAN_FFI_ERROR_NULL_POINTER;
```
Comment (moritzschmitt) [inline src/lib/ffi/ffi_cert.cpp:1405]: The `#else` branches reference parameter names that don't exist, so a build with the FFI but without the x509 module fails. `ffi` lists `x509` as optional in its `info.txt`, so that is a supported configuration. CI doesn't cover it. Reproducer on this branch:

    ./configure.py --disable-modules=x509 --without-documentation
    make build/obj/lib/ffi_cert.o

    src/lib/ffi/ffi_cert.cpp:1251:43: error: use of undeclared identifier 'key'
    src/lib/ffi/ffi_cert.cpp:1398:30: error: use of undeclared identifier 'issuing_cert'
    src/lib/ffi/ffi_cert.cpp:1398:44: error: use of undeclared identifier 'issuing_key'

Line 1251 should name `pubkey`, line 1398 `ca_cert` and `ca_key`. The `#else` branches of `into_self_signed_cert` (line 1212) and `into_cert` (line 1251) also omit `serial_number`, which produces `-Wunused-parameter` warnings in the same build.

**Comment by arckoor** [comment]
Yeah, all still a little rough around the edges, only really tested the happy path for now to be able to provide feedback for the cert builder PR (hence the draft status). The `FFI_EXPORT` macros I will update when it seems reasonable that this PR will make it into a release, it might not even be 3.14.

File: src/python/botan3.py [hunk 2]
```diff
@@ -2491,8 +2571,10 @@ class X509Cert: # pylint: disable=invalid-name
 
     def __init__(self, filename: str | None = None, buf: bytes | None = None):
         """Load a certificate from either a file or a bytestring, but not both"""
-        self.__obj = c_void_p(0)
-        self.__obj = _load_buf_or_file(filename, buf, _DLL.botan_x509_cert_load_file, _DLL.botan_x509_cert_load)
+        if not filename and not buf:
```
Comment (moritzschmitt) [inline src/python/botan3.py:2574]: I ran into the same problem in my TLS FFI work for #2492: the Python binding needs to wrap an `X509Cert` around a handle the library just produced, and `X509Cert.__init__` only knows how to load from a file or a buffer.

I'd suggest not solving it by making `X509Cert()` (and `PKCS10Request()`) legal. With this change a caller who forgets the argument gets an object with a null handle, and every later call on it fails with `BOTAN_FFI_ERROR_NULL_POINTER` instead of the constructor raising. It also changes `X509Cert(buf=b"")`: `_load_buf_or_file` checks `is None`, so an empty buffer used to reach `botan_x509_cert_load` and raise a decoding error, whereas `not buf` now yields the null-handle object silently.

I know `X509CRL` already does this since 7ab352a20, so this is consistent with that. But an alternative that keeps the public constructor strict is a private classmethod that adopts a handle, which is what I ended up with on my branch:

    @classmethod
    def _from_handle(cls, obj: c_void_p) -> X509Cert:
        """Wrap an FFI certificate handle, taking ownership of it"""
        cert = cls.__new__(cls)
        cert._X509Cert__obj = obj
        return cert

`into_self_signed_cert` and friends would then do `obj = c_void_p(0)`, pass `byref(obj)` to the FFI call, and `return X509Cert._from_handle(obj)`. `PublicKey`/`PrivateKey` take the other route and accept an optional `obj` in `__init__`, so either is defensible; I'd just rather not extend the null-handle constructor to two more classes.
