### ISSUE TITLE
Building for IncludeOS

### ISSUE THREAD

**Issue by fwsGonzo** [randombit/botan#726]
We are at a point where we want to try your mighty beast, I suppose, but I get this when I
configure with
```
./configure.py --os=includeos --cpu=x86_32 --disable-shared --cc=clang
```

... and proceed to build on my Linux machine:
```cpp
./src/cli/asn1.cpp:366:34: error: expected ';' after expression
         Botan::DataSource_Stream in(get_arg("file"));
                                 ^
                                 ;
./src/cli/asn1.cpp:366:17: error: no member named 'DataSource_Stream' in namespace 'Botan'
         Botan::DataSource_Stream in(get_arg("file"));
         ~~~~~~~^
./src/cli/asn1.cpp:366:35: error: use of undeclared identifier 'in'
         Botan::DataSource_Stream in(get_arg("file"));
                                  ^
./src/cli/asn1.cpp:368:39: error: use of undeclared identifier 'in'
         if(!Botan::PEM_Code::matches(in))
                                      ^
./src/cli/asn1.cpp:370:40: error: unknown type name 'in'
            Botan::BER_Decoder decoder(in);
                                       ^
./src/cli/asn1.cpp:370:39: warning: parentheses were disambiguated as a function declaration [-Wvexing-parse]
            Botan::BER_Decoder decoder(in);
                                      ^~~~
./src/cli/asn1.cpp:370:40: note: add a pair of parentheses to declare a variable
            Botan::BER_Decoder decoder(in);
                                       ^
                                       (
./src/cli/asn1.cpp:376:64: error: use of undeclared identifier 'in'
            Botan::BER_Decoder decoder(Botan::PEM_Code::decode(in, label));
```

Also, we are in the process of creating a virtual filesystem, and we will be adding /dev/Xrandom soon

**Comment by randombit** [comment]
The CLI currently assumes filesystem support throughout. But since IncludeOS also has no shell there doesn't seem much need for it on that platform. I think you want to use options `--amalgamation --single-amalgamation-file` which will generate `botan_all.cpp` which can be copied into a service seed dir, that at least is the only way I have tried building botan on IncludeOS.

**Comment by fwsGonzo** [comment]
Ok new configure:
```
./configure.py --os=includeos --cpu=x86_32 --disable-shared --single --minimized --amalgamation --enable-modules=sha2_64,tls --cc=clang
```

Results in missing future header, or not included maybe:
```
clang++  -m32 -pthread  -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -c botan_all.cpp -o build/obj/lib/botan_all.o

botan_all.cpp:33603:21: error: no member named 'future' in namespace 'std'
   std::vector<std::future<OCSP::Response>> ocsp_responses;
```

**Comment by AndreasAakesson** [comment]
I've tried to replicate an old patch:
```
--- a/src/lib/x509/x509path.cpp
+++ b/src/lib/x509/x509path.cpp
@@ -86,7 +86,9 @@ check_chain(const std::vector<std::shared_ptr<const X509_Certificate>>& cert_pat
 
    X509_Time validation_time(ref_time);
 
+#if defined(BOTAN_TARGET_OS_HAS_THREADS)
    std::vector<std::future<OCSP::Response>> ocsp_responses;
+#endif
 
    std::vector<std::set<Certificate_Status_Code>> cert_status(cert_path.size());
 
@@ -100,6 +102,7 @@ check_chain(const std::vector<std::shared_ptr<const X509_Certificate>>& cert_pat
 
       std::shared_ptr<const X509_Certificate> issuer = cert_path[at_self_signed_root ? (i) : (i + 1)];
 
+      #if defined(BOTAN_TARGET_OS_HAS_THREADS)
       if(i == 0 || restrictions.ocsp_all_intermediates())
          {
          // certstore[0] is treated as trusted for OCSP (FIXME)
@@ -108,6 +111,7 @@ check_chain(const std::vector<std::shared_ptr<const X509_Certificate>>& cert_pat
                std::async(std::launch::async,
                           OCSP::online_check, *issuer, *subject, certstores[0]));
          }
+      #endif
 
       // Check all certs for valid time range
       if(validation_time < X509_Time(subject->start_time(), ASN1_Tag::UTC_OR_GENERALIZED_TIME))
@@ -161,6 +165,7 @@ check_chain(const std::vector<std::shared_ptr<const X509_Certificate>>& cert_pat
       std::shared_ptr<const X509_Certificate> subject = cert_path.at(i);
       std::shared_ptr<const X509_Certificate> ca = cert_path.at(i+1);
 
+      #if defined(BOTAN_TARGET_OS_HAS_THREADS)
       if(i < ocsp_responses.size())
          {
          try
@@ -184,6 +189,7 @@ check_chain(const std::vector<std::shared_ptr<const X509_Certificate>>& cert_pat
             //std::cout << "OCSP error: " << e.what() << "\n";
             }
          }
+      #endif
```

But then it leads me to Clang fatal error:
```
atal error: error in backend: Cannot select: intrinsic %llvm.x86.aesni.aesenclast
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 3.8.0 (tags/RELEASE_380/final)
Target: i386-apple-darwin15.6.0
```

So I've tried with the `--disable-aes-ni`, which results in:
```
botan_all.cpp:41807:30: error: unknown type name '__m256i'
inline void interleave_epi64(__m256i& X0, __m256i& X1)
                             ^
botan_all.cpp:41807:43: error: unknown type name '__m256i'
inline void interleave_epi64(__m256i& X0, __m256i& X1)
                                          ^
botan_all.cpp:41812:10: error: unknown type name '__m256i'
   const __m256i T0 = _mm256_unpacklo_epi64(X0, X1);
         ^
botan_all.cpp:41813:10: error: unknown type name '__m256i'
   const __m256i T1 = _mm256_unpackhi_epi64(X0, X1);
         ^
```

**Comment by fwsGonzo** [comment]
We might be willing to upgrade to using AVX, however I dont see much integer arithmetic for AVX1, so is there any point? And why is there avx2 instrinsics there :P Too new!

**Comment by randombit** [comment]
For such situations there is always `--disable-avx2` ;P

Strange though, the ISA annotations added in 1.11.33 should allow these functions to compile without any extra compiler flags being required. That works with GCC at least, Clang 3.7 is documented as having the same attribute but perhaps it does not work exactly the same way.

**Comment by fwsGonzo** [comment]
Do you have any use for plain AVX at all? No integer stuff, and we might be able to support that since its 2011

**Comment by randombit** [comment]
No need for AVX floating point.

**Comment by randombit** [comment]
@fwsGonzo Can you try the `ocsp-network` branch (from PR #653)? It should compile cleanly for IncludeOS. That PR should land on master shortly (or before next release, anyway).

**Comment by randombit** [comment]
@fwsGonzo can you try latest master?

**Comment by fwsGonzo** [comment]
We have lift off, with the amalgamation build at least ;) :+1:

**Comment by alfred-bratterud** [comment]
@randombit We've now been able to build Botan for IncludeOS as a static library without the amalgamation build. In short we had to add include paths to our own libc++, libc and ./api/sys which we snuck in via `--cc-abi-flags` together with`-D_LIBCPP_HAS_NO_THREADS=1 -nostdlib -stdlib=libc++`.  We also set `--cc=clang`. We can however not build the cli client and tests since these rely on `std::async`, but we also don't need them. Is there a simple way to install only the library? I can build it with `make libbotan-1.11` but I couldn't see how to install the headers without make also trying to build the client. The good news is that once we point an IncludeOS service to the produced static library and headers we can use e.g. sha1/sha256 hashing with correct results.

**Comment by AndreasAakesson** [comment]
I built botan for IncludeOS on Mac with the toolchain above + some other fixes.

Is it possible to get a configure target where client isn't included? Currently I have to do something like this:

* `./configure` for includeos with a lot of extra params
* Open Makefile and edit `AR` to be equal i686-ar (binutils installed with IncludeOS toolchain for mac)
* `make -j` and then `make` again. Now it fails to build client but library is good
*  Copy library to `/usr/local/lib`
* Copy headers to `/usr/local/include/libbotan`

I also made a tiny change in botan to be able to use the RNG you implemented :)
```
diff --git a/src/lib/rng/system_rng/info.txt b/src/lib/rng/system_rng/info.txt
index 987b18c..0cfd232 100644
--- a/src/lib/rng/system_rng/info.txt
+++ b/src/lib/rng/system_rng/info.txt
@@ -20,4 +20,5 @@ openbsd
 qnx
 solaris
 windows
+includeos
 </os>
```

**Comment by randombit** [comment]
Right now building without the client app is not possible. But in cases where we do not expect there to be a filesystem or shell on the target system, it really should be skipped.

I added the fix to use the random device, and also added a `libs` target to the makefiles. So you can use `make libs` to get a library binary without encountering any make errors, and even then use `./src/scripts/install.py --destdir=foo` to perform the install if you like.

**Comment by fwsGonzo** [comment]
This is for the most part solved for now. :+1:
